<#
.SYNOPSIS
    Generate a secure .env file for the Ride-Hailing project.

.DESCRIPTION
    Generates random secrets for JWT, internal communication,
    PostgreSQL databases and Redis.

    The script will NOT overwrite an existing .env file.

.EXAMPLE
    .\scripts\gen-env.ps1
#>

$ErrorActionPreference = 'Stop'

$rootDir = Split-Path $PSScriptRoot
$envFile = Join-Path $rootDir '.env'

# Do not overwrite an existing .env
if (Test-Path $envFile) {
    Write-Warning "The .env file already exists: $envFile"
    Write-Warning "The script will NOT overwrite it."
    Write-Warning "Delete or rename the existing .env if you want to generate a new one."
    exit 1
}

Write-Host "Generating secure .env..." -ForegroundColor Cyan

function New-RandomBytes {
    param(
        [Parameter(Mandatory = $true)]
        [int]$Count
    )

    $bytes = New-Object byte[] $Count
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()

    try {
        $rng.GetBytes($bytes)
    }
    finally {
        $rng.Dispose()
    }

    return $bytes
}

function To-Base64 {
    param(
        [Parameter(Mandatory = $true)]
        [byte[]]$Bytes
    )

    return [Convert]::ToBase64String($Bytes)
}

function To-Hex {
    param(
        [Parameter(Mandatory = $true)]
        [byte[]]$Bytes
    )

    return ($Bytes | ForEach-Object {
        '{0:x2}' -f $_
    }) -join ''
}

# Generate secrets
$jwtSecret = To-Base64 (New-RandomBytes -Count 48)
$internalKey = To-Hex (New-RandomBytes -Count 32)

$postgresPass = To-Hex (New-RandomBytes -Count 24)
$userDbPass = To-Hex (New-RandomBytes -Count 24)
$locationDbPass = To-Hex (New-RandomBytes -Count 24)
$dispatchDbPass = To-Hex (New-RandomBytes -Count 24)
$paymentDbPass = To-Hex (New-RandomBytes -Count 24)

$redisPass = To-Hex (New-RandomBytes -Count 24)

$generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

$envContent = @"
# =============================================================================
# Ride-Hailing & Logistics - Environment Variables
# Generated by scripts/gen-env.ps1
# Generated at: $generatedAt
# =============================================================================

# ---- Security ---------------------------------------------------------------

JWT_SECRET=$jwtSecret
INTERNAL_KEY=$internalKey

# ---- PostgreSQL -------------------------------------------------------------

POSTGRES_PASSWORD=$postgresPass
USER_DB_PASSWORD=$userDbPass
LOCATION_DB_PASSWORD=$locationDbPass
DISPATCH_DB_PASSWORD=$dispatchDbPass
PAYMENT_DB_PASSWORD=$paymentDbPass
POSTGRES_PORT=5432

# ---- Redis ------------------------------------------------------------------

REDIS_PASSWORD=$redisPass
REDIS_PORT=6379

# ---- CORS -------------------------------------------------------------------

CORS_ALLOWED_ORIGINS=https://ridehailing.duckdns.org

# ---- Docker image -----------------------------------------------------------

IMAGE_TAG=latest
"@

# Write .env as UTF-8
Set-Content `
    -Path $envFile `
    -Value $envContent `
    -Encoding UTF8

Write-Host ""
Write-Host ".env generated successfully." -ForegroundColor Green
Write-Host "Location: $envFile" -ForegroundColor Green
Write-Host ""

Write-Host "Security information:" -ForegroundColor Yellow
Write-Host "- JWT_SECRET and INTERNAL_KEY were generated randomly."
Write-Host "- Database and Redis passwords were generated randomly."
Write-Host "- Secrets were NOT printed to the console."
Write-Host "- The existing .env file was not overwritten."
Write-Host ""

Write-Host "IMPORTANT:" -ForegroundColor Yellow
Write-Host "- Database passwords only initialize PostgreSQL when the database volume is empty."
Write-Host "- Keep the .env file private."
Write-Host "- Do NOT commit .env to Git."
Write-Host "- Do NOT push .env to GitHub."
Write-Host ""

Write-Host "Docker commands:" -ForegroundColor Cyan
Write-Host "  docker compose up -d"
Write-Host "  docker compose --profile apps up -d"
Write-Host "  docker compose --profile apps --profile ha up -d"
