<#
.SYNOPSIS
    Sinh file .env với giá trị ngẫu nhiên an toàn cho Ride-Hailing project.

.DESCRIPTION
    Script tạo file .env từ .env.example với các giá trị ngẫu nhiên:
    - JWT_SECRET: base64 48 byte (96 ký tự)
    - INTERNAL_KEY: hex 32 byte (64 ký tự)
    - POSTGRES_PASSWORD, USER_DB_PASSWORD, LOCATION_DB_PASSWORD, DISPATCH_DB_PASSWORD, PAYMENT_DB_PASSWORD: hex 24 byte (48 ký tự)
    - REDIS_PASSWORD: hex 24 byte (48 ký tự)

    KHÔNG ghi đè file .env nếu đã tồn tại.

.EXAMPLE
    .\scripts\gen-env.ps1

.NOTES
    Yêu cầu PowerShell 5.1+ hoặc PowerShell Core 6+
#>

# Dừng nếu có lỗi
$ErrorActionPreference = 'Stop'

$rootDir = Split-Path $PSScriptRoot
$envFile = Join-Path $rootDir '.env'
$exampleFile = Join-Path $rootDir '.env.example'

# Kiểm tra .env đã tồn tại chưa
if (Test-Path $envFile) {
    Write-Warning "File .env đã tồn tại tại: $envFile"
    Write-Warning "Script KHÔNG ghi đè. Hãy xóa hoặc đổi tên .env cũ nếu muốn sinh lại."
    exit 1
}

# Kiểm tra .env.example
if (-not (Test-Path $exampleFile)) {
    Write-Error "Không tìm thấy .env.example tại: $exampleFile"
    exit 1
}

Write-Host "Đang sinh file .env với giá trị ngẫu nhiên..." -ForegroundColor Cyan

# Hàm sinh bytes ngẫu nhiên và chuyển sang base64/hex
function New-RandomBytes {
    param(
        [int]$Count
    )
    $bytes = New-Object byte[] $Count
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    return $bytes
}

function To-Base64 {
    param([byte[]]$Bytes)
    return [Convert]::ToBase64String($Bytes)
}

function To-Hex {
    param([byte[]]$Bytes)
    return ($Bytes | ForEach-Object { '{0:x2}' -f $_ }) -join ''
}

# Sinh các giá trị ngẫu nhiên
$jwtSecretBytes = New-RandomBytes -Count 48
$internalKeyBytes = New-RandomBytes -Count 32
$postgresPassBytes = New-RandomBytes -Count 24
$userDbPassBytes = New-RandomBytes -Count 24
$locationDbPassBytes = New-RandomBytes -Count 24
$dispatchDbPassBytes = New-RandomBytes -Count 24
$paymentDbPassBytes = New-RandomBytes -Count 24
$redisPassBytes = New-RandomBytes -Count 24

$jwtSecret = To-Base64 $jwtSecretBytes
$internalKey = To-Hex $internalKeyBytes
$postgresPass = To-Hex $postgresPassBytes
$userDbPass = To-Hex $userDbPassBytes
$locationDbPass = To-Hex $locationDbPassBytes
$dispatchDbPass = To-Hex $dispatchDbPassBytes
$paymentDbPass = To-Hex $paymentDbPassBytes
$redisPass = To-Hex $redisPassBytes

# Tạo nội dung .env trực tiếp (không dùng regex trên template để tránh lỗi encoding)
$envContent = @"
# =============================================================================
# Ride-Hailing & Logistics - Environment Variables
# Generated by scripts/gen-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# =============================================================================

# ---- BẮT BUỘC (Compose sẽ báo lỗi nếu thiếu) --------------------------------
JWT_SECRET=$jwtSecret
INTERNAL_KEY=$internalKey

# ---- POSTGRES (mặc định cho dev local; trên VPS PHẢI đặt trong .env) ---------
POSTGRES_PASSWORD=$postgresPass
USER_DB_PASSWORD=$userDbPass
LOCATION_DB_PASSWORD=$locationDbPass
DISPATCH_DB_PASSWORD=$dispatchDbPass
PAYMENT_DB_PASSWORD=$paymentDbPass
POSTGRES_PORT=5432

# ---- REDIS (mặc định cho dev local; trên VPS PHẢI đặt trong .env) ------------
REDIS_PASSWORD=$redisPass
REDIS_PORT=6379

# ---- CORS cho api-gateway (phân tách bằng dấu phẩy, để trống = không bật) ----
CORS_ALLOWED_ORIGINS=

# ---- Tag image (mặc định local build) ----------------------------------------
IMAGE_TAG=local
"@

# Ghi file .env
Set-Content -Path $envFile -Value $envContent -Encoding UTF8

Write-Host "Đã tạo file .env tại: $envFile" -ForegroundColor Green
Write-Host ""
Write-Host "Các giá trị đã sinh:" -ForegroundColor Cyan
Write-Host "  JWT_SECRET = $jwtSecret"
Write-Host "  INTERNAL_KEY = $internalKey"
Write-Host "  POSTGRES_PASSWORD = $postgresPass"
Write-Host "  USER_DB_PASSWORD = $userDbPass"
Write-Host "  LOCATION_DB_PASSWORD = $locationDbPass"
Write-Host "  DISPATCH_DB_PASSWORD = $dispatchDbPass"
Write-Host "  PAYMENT_DB_PASSWORD = $paymentDbPass"
Write-Host "  REDIS_PASSWORD = $redisPass"
Write-Host ""
Write-Host "Lưu ý:" -ForegroundColor Yellow
Write-Host "  - JWT_SECRET và INTERNAL_KEY là BẮT BUỘC (Compose sẽ báo lỗi nếu thiếu)"
Write-Host "  - Mật khẩu DB/Redis chỉ có tác dụng khi volume Postgres/Redis còn trống (lần khởi tạo đầu)"
Write-Host "  - Trên VPS, hãy copy file .env này và lưu trữ an toàn"
Write-Host ""
Write-Host "Để chạy stack:" -ForegroundColor Cyan
Write-Host "  docker compose up -d                    # Chỉ hạ tầng (postgres, redis)"
Write-Host "  docker compose --profile apps up -d     # Toàn bộ 7 service"
Write-Host "  docker compose --profile apps --profile ha up -d  # Với ws-gateway replica"