$env:SERVER_PORT="8082"
$env:DB_URL="jdbc:postgresql://localhost:5432/location"
$env:DB_USERNAME="location_app"
$env:DB_PASSWORD="location-local-only"
$env:REDIS_HOST="localhost"
$env:REDIS_PASSWORD="b9a0a42e0959afc1564503eba0fbaa67418e0966e5fd7969"
$env:JWT_SECRET="test-secret-key-32-chars-minimum"
$env:INTERNAL_KEY="test-internal-key"
$env:USER_SERVICE_URL="http://localhost:8081"
$env:LOCATION_SERVICE_URL="http://localhost:8082"
$env:DISPATCH_SERVICE_URL="http://localhost:8083"
$env:PRICING_SERVICE_URL="http://localhost:8084"
$env:PAYMENT_SERVICE_URL="http://localhost:8085"
$env:WS_GATEWAY_URL="http://localhost:8001"

mvn -pl location-service spring-boot:run -D"spring-boot.run.profiles=infra"