server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

spring:
  application:
    name: location-service
  threads:
    virtual:
      enabled: true
  main:
    allow-bean-definition-overriding: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /api/v1
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true