spring:
  config:
    activate:
      on-profile: infra
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

services:
  location: ${LOCATION_SERVICE_URL}
  dispatch: ${DISPATCH_SERVICE_URL}
