spring:
  config:
    activate:
      on-profile: infra
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

services:
  location: ${LOCATION_SERVICE_URL}
  dispatch: ${DISPATCH_SERVICE_URL}
